# Generated by Django 2.1.4 on 2018-12-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbla_admin', '0002_auto_20181231_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='book_images'),
        ),
    ]
