# Generated by Django 2.1.4 on 2018-12-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbla_admin', '0005_auto_20181231_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
