# Generated by Django 2.1.4 on 2018-12-31 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbla_admin', '0006_auto_20181231_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='book_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='fbla_admin.book'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='check_out_student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='fbla_admin.student'),
        ),
    ]
