# Generated by Django 2.1.4 on 2019-01-01 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbla_admin', '0008_auto_20190101_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='book_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='fbla_admin.book'),
        ),
    ]
