# Generated by Django 2.1.4 on 2019-01-01 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbla_admin', '0009_auto_20190101_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='book_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='fbla_admin.book'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='check_out_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='fbla_admin.student'),
        ),
    ]
