# Generated by Django 2.2 on 2019-05-07 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbla_admin', '0010_auto_20190101_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='book_id',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='fbla_admin.book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ebook',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Claim Code'),
        ),
    ]
